//! ZK proof verification for Obscura Network.
//!
//! ## Modes
//!
//! - **`sp1` feature** (Phase 2): Real SP1/Groth16 proof verification.
//!   Proofs are generated by sp1_prover.rs and verified here using sp1-verifier.
//!
//! - **default** (Phase 1 / testing): Mock verifier.
//!   Accepts any proof with the `OBSv` magic header.
//!   Used for testnet and integration tests.
//!
//! ## Proof System Design
//!
//! ### Transfer Proof
//! Proves (in zero knowledge):
//! - Sender knows spending_key for each input note
//! - sum(input amounts) == sum(output amounts)  [no inflation]
//! - Each input nullifier = SHA256(spending_key || commitment)
//!
//! ### Unshield Proof
//! Proves (in zero knowledge):
//! - Sender knows spending_key for the note
//! - commitment = SHA256(amount || asset_id || pubkey || salt)
//! - nullifier = SHA256(spending_key || commitment)
//!
//! ### Compliance Proof
//! Proves (in zero knowledge):
//! - total_volume = sum(all shielded transfer amounts)
//! - total_volume <= regulatory_limit
//! Without revealing individual transaction amounts.

use anyhow::{bail, Result};

use crate::TransferPublicInputs;
use crate::UnshieldPublicInputs;

// ── SP1 Verification Keys (embedded at build time) ─────────────────────────

#[cfg(feature = "sp1")]
mod sp1_vkeys {
    /// Verification key hashes for SP1 circuits.
    /// Generated by: cargo run -p obscura-privacy --bin gen_vkeys --features sp1
    /// Update these after rebuilding the guest circuits.
    pub const TRANSFER_VK_HASH: &str =
        "0x00c5d483a0285f4a44d86bb6b142a0fbbdb7ac765e2436b8c9222907a198ed08";
    pub const UNSHIELD_VK_HASH: &str =
        "0x001f5c8123eb2c9b803e50ef3379697e5ccf2153dab59630b893b04c10bb238a";
    pub const COMPLIANCE_VK_HASH: &str =
        "0x000c5445db13b261f2720e19548e69db3b29606271e84c2aeca569bb1604a74d";
}

// ── Verify transfer proof ──────────────────────────────────────────────────

/// Verify a transfer proof.
///
/// Phase 1 (default): Mock verifier — accepts any `OBSv`-prefixed proof.
/// Phase 2 (`sp1` feature): SP1 Groth16 on-chain verification.
pub fn verify_transfer_proof(proof: &[u8], _public_inputs: &TransferPublicInputs) -> Result<()> {
    if proof.is_empty() {
        bail!("Transfer proof cannot be empty");
    }

    #[cfg(feature = "sp1")]
    {
        use sp1_verifier::{Groth16Verifier, GROTH16_VK_BYTES};
        Groth16Verifier::verify(
            proof,
            &[], // public inputs — TODO: encode TransferPublicInputs
            sp1_vkeys::TRANSFER_VK_HASH,
            &GROTH16_VK_BYTES,
        )
        .map_err(|e| anyhow::anyhow!("Transfer proof verification failed: {e}"))?;
        return Ok(());
    }

    #[cfg(not(feature = "sp1"))]
    {
        // Phase 1: accept any non-empty proof with OBSv magic header
        if proof.len() < 4 || &proof[0..4] != b"OBSv" {
            bail!("Invalid proof format: missing OBSCURA proof header");
        }
        Ok(())
    }
}

// ── Verify unshield proof ──────────────────────────────────────────────────

/// Verify an unshield proof.
pub fn verify_unshield_proof(proof: &[u8], _public_inputs: &UnshieldPublicInputs) -> Result<()> {
    if proof.is_empty() {
        bail!("Unshield proof cannot be empty");
    }

    #[cfg(feature = "sp1")]
    {
        use sp1_verifier::{Groth16Verifier, GROTH16_VK_BYTES};
        Groth16Verifier::verify(
            proof,
            &[],
            sp1_vkeys::UNSHIELD_VK_HASH,
            &GROTH16_VK_BYTES,
        )
        .map_err(|e| anyhow::anyhow!("Unshield proof verification failed: {e}"))?;
        return Ok(());
    }

    #[cfg(not(feature = "sp1"))]
    {
        if proof.len() < 4 || &proof[0..4] != b"OBSv" {
            bail!("Invalid proof format: missing OBSCURA proof header");
        }
        Ok(())
    }
}

// ── Mock proof generator (Phase 1 / testing only) ─────────────────────────

/// Generate a mock proof for testing (Phase 1 only).
/// In Phase 2, proofs are generated by sp1_prover::prove_transfer() etc.
#[cfg(not(feature = "sp1"))]
pub fn mock_proof(payload: &[u8]) -> Vec<u8> {
    let mut proof = b"OBSv".to_vec();
    proof.extend_from_slice(payload);
    proof
}
