[package]
name = "obscura-bridge-guest-sp1"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]

[dependencies]
sp1-zkvm     = { version = "6.0.2" }
sha2         = { version = "0.10", default-features = false }
serde        = { version = "1", features = ["derive"], default-features = false }
borsh        = { version = "1", features = ["derive"], default-features = false }
rlp          = { version = "0.5", default-features = false, features = ["std"] }
tiny-keccak  = { version = "2", features = ["keccak"] }

[patch.crates-io]
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.9.9-sp1-6.0.0" }
sha2-v0-10-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.9-sp1-6.0.0" }

[profile.release]
opt-level = 3
lto = true

[profile.release.build-override]
opt-level = 3
